runtime: go111

handlers:
  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  - url: /
    static_files: public/index.html
    upload: public/index.html

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
